europe_countries = [
    "Albania",
    "Andorra",
    "Austria",
    "Belgia",
    "Białoruś",
    "Bośnia i Hercegowina",
    "Bułgaria",
    "Chorwacja",
    "Cypr",
    "Czechy",
    "Dania",
    "Estonia",
    "Finlandia",
    "Francja",
    "Grecja",
    "Hiszpania",
    "Holandia",
    "Irlandia",
    "Islandia",
    "Kosowo",
    "Liechtenstein",
    "Litwa",
    "Luksemburg",
    "Łotwa",
    "Malta",
    "Mołdawia",
    "Monako",
    "Niemcy",
    "Norwegia",
    "Polska",
    "Portugalia",
    "Rumunia",
    "San Marino",
    "Serbia",
    "Słowacja",
    "Słowenia",
    "Szwajcaria",
    "Szwecja",
    "Turcja",
    "Ukraina",
    "Węgry",
    "Wielka Brytania",
    "Włochy"
]